#pragma once

#include <iostream>
#include <xaudio2.h>
#include <string>
#include <algorithm>
#include <Windows.h>
#include <winuser.h>
#include <cmath>
#include <chrono>
#include <thread>
#include <map>
#include <time.h>
#include <random>
#include <fstream>
#include <conio.h>
#include <vector>
#include <sstream>
#include <iomanip>
#include <cstdlib> 
#include <ctime>

#include "Audio.h"
#include "Entity.h"
#include "Frame.h"
#include "Item.h"
#include "Lane.h"
#include "Map.h"
#include "Pixel.h"
#include "Movable.h"
#include "Player.h"
#include "resource.h"
#include "Screen.h"
#include "Sprite.h"
#include "Supportive.h"
#include "Text.h"
#include "Texture.h"
#include "TrafficLight.h"
#include "Utilities.h"